# Generated by Django 4.2.10 on 2024-02-14 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TechnoCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbstractUser',
            new_name='UserProfile',
        ),
    ]
